name: B918
on:
  workflow_dispatch:
    inputs:
      clean_cache:
        description: 'Clear caches'
        required: false
        type: boolean
 # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths:
      - "docker/**"
      - "**.sh"
      - "**.json"
  pull_request:
    branches: [ master ]
    paths:
      - "docker/**"
      - "**.sh"
      - "**.json"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
   
      - name: Chmod
        run: chmod 0755 ./redpill_tool_chain.sh

      - name: Add Extensions
        run: |
          ./redpill_tool_chain.sh add https://github.com/tossp/redpill-tool-chain/raw/master/extensions/redpill-boot-wait.json
          ./redpill_tool_chain.sh add https://github.com/tossp/redpill-tool-chain/raw/master/extensions/redpill-acpid.json
          ./redpill_tool_chain.sh add https://github.com/tossp/redpill-tool-chain/raw/master/extensions/redpill-virtio.json
          ./redpill_tool_chain.sh add https://raw.githubusercontent.com/pocopico/rp-ext/main/igbvf/rpext-index.json
          ./redpill_tool_chain.sh add https://raw.githubusercontent.com/pocopico/rp-ext/main/e1000/rpext-index.json
          ./redpill_tool_chain.sh add https://raw.githubusercontent.com/pocopico/rp-ext/main/igb/rpext-index.json
          ./redpill_tool_chain.sh add https://raw.githubusercontent.com/pocopico/rp-ext/main/vmxnet3/rpext-index.json
          ./redpill_tool_chain.sh add https://raw.githubusercontent.com/pocopico/rp-ext/main/hv_netvsc/rpext-index.json
          ./redpill_tool_chain.sh add https://raw.githubusercontent.com/pocopico/rp-ext/main/vmw_pvscsi/rpext-index.json      
          
      - name: 添加 Misc shell
        run: |
          ./redpill_tool_chain.sh add https://github.com/tossp/redpill-tool-chain/raw/master/extensions/redpill-misc.json
          
      - name: Build docker image
        run: ./redpill_tool_chain.sh build ds918p-7.0.1-42218
      - name: Create dsm image
        run: ./redpill_tool_chain.sh auto ds918p-7.0.1-42218

      - uses: actions/upload-artifact@v2
        with:
          name: dsm918
          path: ./images
